version: '3.8'

services:
  # Web Server (Nginx)
  webserver:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  # PHP Service
  php:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: sqluser
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Composer Service
  composer:
    image: composer:latest
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["composer"]

  node:
    image: node:18-alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    entrypoint: ["npm"]
    ports:
      - "5173:5173" 
    depends_on:
      - php

volumes:
  mysql_data: